CREATE DATABASE shop;
USE shop;

CREATE TABLE IF NOT EXISTS Material (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Title VARCHAR(100) NOT NULL,
	CountInPack INT NOT NULL,
	Unit VARCHAR(10) NOT NULL,
	MaterialType VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS Product (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	Title VARCHAR(100) NOT NULL,
	ProductType VARCHAR(100) NOT NULL,
	Description LONGTEXT NULL,
	Image VARCHAR(100) NULL,
	Cost DECIMAL(10,2) NOT NULL,
	RegisterDate DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS ProductMaterial (
	ProductID INT NOT NULL,
	MaterialID INT NOT NULL,
	Count DOUBLE NULL,
	PRIMARY KEY (ProductID, MaterialID),
	FOREIGN KEY (MaterialID) REFERENCES Material (ID),
	FOREIGN KEY (ProductID) REFERENCES Product (ID)
);
